### ISSUE TITLE
Response state param did not match request state

### ISSUE THREAD

**Issue by merijndejonge** [okta/okta-oidc-android#167]
Hello,

I implemented logout functionality in my android app. But when the user logs in again after he has logged out I get the exception from okta android client:

    `java.lang.Error: AuthorizationException: {"type":0,"code":9,"errorDescription":"Response state param did not match request state"}`

There might be some CSRF left, but how to get rid of this?

I signout with `webAuth.signOutOfOkta()` and after that has completed, I call `webAuth.sessionClient.clear()`.

Any suggestions?

**Comment by ghostship** [comment]
Any update on this?

**Comment by FeiChen-okta** [comment]
Hi @ghostship are you using the latest SDK? This issue might of been fixed with https://github.com/okta/okta-oidc-android/pull/175

**Comment by ghostship** [comment]
@FeiChen-okta 
Updated to 1.0.15 and is still an issue. 
`validateResult()` in `AuthAPI.java` is comparing request and result state and it looks like request state is a string and `responseState` is null.

FWIW, `authClient.signIn()` was successful for a while. Now I get this response for every call

**Comment by FeiChen-okta** [comment]
responseState should not be null. Can you check your server side configuration? In Generate App settings it should look something like
![Screen Shot 2020-08-17 at 5 50 48 PM](https://user-images.githubusercontent.com/46411069/90459789-273a7180-e0b7-11ea-8ea5-faf8df203839.png)

![Screen Shot 2020-08-17 at 5 50 55 PM](https://user-images.githubusercontent.com/46411069/90459794-2b668f00-e0b7-11ea-8d9e-d8837d1b6c70.png)

**Comment by ghostship** [comment]
Changed to those settings and it did not affect anything.

I did find the culprit however. I disabled the multi-factor Sign On policy that I had in place and got a success.
Reenabling the policy, and I get the same error. Here are the configuration settings:

<img width="776" alt="Screen Shot 2020-08-18 at 1 34 34 AM" src="https://user-images.githubusercontent.com/533630/90484408-5c64b500-e0f3-11ea-88df-4170214f8d09.png">

**Comment by FeiChen-okta** [comment]
Hi @ghostship It looks like you are using custom login instead of chrome custom tabs using okta's sign in widget. In this case you would have to handle the MFA states in `AuthenticationClient` This is a separate SDK used to interact with [Okta's Authentication API](https://developer.okta.com/docs/reference/api/authn/). For more information about the authn SDK https://github.com/okta/okta-auth-java

We don't have an example of MFA handling for the sample app. It only shows simple login with password. You will have to handle the MFA states in https://github.com/okta/okta-oidc-android/blob/master/app/src/main/java/com/okta/oidc/example/SampleActivity.java#L636

For example in `handleMfaEnroll` you'll need to have a UI that instructs your users to start MFA enrollment similar to the web login.

**Comment by JayNewstrom** [comment]
Looks like Fei was able to answer questions in this issue. Please feel free to comment, reopen, or open a new issue with any further questions. Thanks!
